server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    instance-id: 8761
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka
logging:
  level:
    com.netflix.eureka: DEBUG

